---
title: "model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(gridExtra)
library(cluster)
library(factoextra)
```

```{r}
urlfile <- "https://raw.githubusercontent.com/jlin99/DataFest-2020/master/data/covid%20impact%20survey/wk1.new.csv"
data <- read.csv(url(urlfile))

urlfile2 <- "https://raw.githubusercontent.com/jlin99/DataFest-2020/master/data/covid%20impact%20survey/imp_long_new.csv"
imp_data <- read.csv(url(urlfile2))

clean_data <- function(data) {

  #Delete question answers deemed unusable for our model (due to complexity, irrelevance, redundancy, etc.)
  #PHYS11, PHYS11TEMP, ECON2, ECON4, HH****, MODE, LANGUAGE, etc.
  
  drops <- c("PHYS11", "PHYS11_TEMP", "HH01S", "HH25S", "HH612S", "HH1317S", "HH18OVS", "P_OCCUPY2", "MODE", "MAIL50", "HH_BANNER", "EDUC4", "INC_BANNER", "AGE_BANNER", "AGE4", "RACE2_BANNER", "RACETH", "RACE_R2", "NATIONAL_WEIGHT", "REGION_WEIGHT", "NATIONAL_WEIGHT_POP", "REGION_WEIGHT_POP", "NAT_WGT_COMB_POP", "REG_WGT_COMB_POP", "P_GEO", "P_PANEL", "SU_ID", "LANGUAGE", "ECON2", "ECON4", ".imp", ".id")
  data_mod_test <- data[ , !(names(data) %in% drops)]
  
  #Code was originally written for original dataset, imputated data is in different order
  #Reorder columns so code can be used again 
  
  data_mod <- data_mod_test[,c(1:31,105:126,32:55,127:137,56:72,138:144,73:104,145)]
  

  #Next we form our first feature, SOC Score
  #Because we are looking at mental health in COVID times, socialization pre-COVID does not help us
  #Instead we are replacing those columns with change in socialization (delta)
  #We do A - B because we want a lower score to indicate good social health (talking to people)
  #If there is a dramatic shift from frequently socializing (1) to not socializing at all (5), we want to mark that as a higher score since that is presumably bad. Hence, 5-1 makes more sense.
  
  data_mod$SOC2_delta <- data_mod$SOC2A - data_mod$SOC2B
  data_mod$SOC3_delta <- data_mod$SOC3A - data_mod$SOC2B
  
  #In order to remain with theme of lower social health is better, we need to reverse answers of PHYS6
  
  for (i in 1:length(data_mod$PHYS6)){
    if ( isTRUE(data_mod$PHYS6[i] == 1)){
      data_mod$PHYS6[i] = 2
    }
    else if ( isTRUE(data_mod$PHYS6[i] == 2)){
      data_mod$PHYS6[i] = 1
    }
  }
  
  #Next, our SOC score is made up of SOC1, SOC2A, SOC2_delta, SOC3A, SOC3_delta, SOC4A, SOC4B, PHYS6
  #min score = -2, max score = 28
  
  data_mod <- data_mod %>%
    mutate(SOC_Score = rowSums(cbind(data_mod$SOC1, data_mod$SOC2, data_mod$SOC2_delta, data_mod$SOC3A, data_mod$SOC3_delta, data_mod$SOC4A, data_mod$SOC4B, data_mod$PHYS6)))
  
  #Make PHYS score
  #For similar reasons, I need to reverse some of the columns in this section
  
  phys_rev <- c(10:26, 121:135)
  dict1 = c(2:1)
  
  for (i in phys_rev){
    for (j in 1:length(data_mod[,i])){
      data_mod[j,i] = dict1[data_mod[j,i]]
    }
  }
  
  
  #Made up of PHYS8, PHYS1A:PHYS1Q, PHYS7_1:PHYS7_4, PHYS3A:PHYS3M, PHYS4, PHYS5
  #min score = 33, max score = 75
  
  
  phys_col <- c(9:26,106:109,121:135)
  
  data_mod <- data_mod %>%
    mutate(PHYS_Score = rowSums(data_mod[,phys_col]))
  
  #Make RESPONSE score 
  #There is one answer that also needs to be reversed
  
  resp_rev <- c(32:50)
  
  for (i in resp_rev){
    for (j in 1:length(data_mod[,i])){
      if (isTRUE(data_mod[j,i] == 0)){
        data_mod[j,i] = 1
      }
      else if (isTRUE(data_mod[j,i] == 1)){
        data_mod[j,i] = 0
      }
    }
  }
  
  
  #Made up of PHYS2_1:PHYS2_19, PHYS10A:PHYS10E, ECON8A:ECON8S
  #min score = 24, max score = 82
  
  resp_col <- c(32:50, 54:77)
  
  data_mod <- data_mod %>%
    mutate(RESP_Score = rowSums(data_mod[,resp_col]))
  #Make ECON score
  
  #We also need to reverse some of the ECON scores
  
  econ_rev1<- c(92:103)
  econ_rev2 <- c(104,105)
  
  dict2 = c(4:1)
  
  for (i in econ_rev1){
    for (j in 1:length(data_mod[,i])){
      data_mod[j,i] = dict2[data_mod[j,i]]
    }
  }
  
  dict3 = c(3:1)
  
  for (i in econ_rev2){
    for (j in 1:length(data_mod[,i])){
      data_mod[j,i] = dict3[data_mod[j,i]]
    }
  }
  
  dict = c(18:1)
  
  for (j in 1:length(data_mod[,144])){
    data_mod[j,144] = dict[data_mod[j,144]]
  }
  #Made up of ECON7, ECON1, ECON4A, ECON4B, ECON6A:ECON6L, ECON5A:ECON5B, INCOME
  #min score = 18, max score = 93
  
  econ_col <- c(78:85, 89:105, 144)
  
  data_mod <- data_mod %>%
    mutate(ECON_Score = rowSums(data_mod[,econ_col]))
  
  #Lastly, we include gender, race, educat, hhsize, etc. in our data frame for our model
  
  model_col <- c(145, 148:151, 137:142)
  
  data_model <- data_mod[,model_col]
  
  #Scale SOC, PHYS, RESP, and ECON scores so people can rate themselves on a scale from 0-10
  #Lower score indicates "better". So a low PHYS score would mean little to no symptoms
  #Low SOC -> socializing regularly, low RESP -> takes more precatuions, low ECON -> no money troubles
  scalescores <- c(2:5)
  for (i in scalescores){
    data_model[,i] <- (data_model[,i]-min(data_model[,i], na.rm=T))*10/
      (max(data_model[,i], na.rm=T)-min(data_model[,i], na.rm=T))
  }

return (data_model)
}
```

```{r}
#imp stands for multiple imputation
#Ran it 5 times due to it having randomness
imp_data1 = imp_data[8791:17580,]
imp_data2 = imp_data[17581:26370,]
imp_data3 = imp_data[26371:35160,]
imp_data4 = imp_data[35161:43950,]
imp_data5 = imp_data[43951:52740,]

#We want to run all 5 models to make sure that all 5 look relatively similar
#We will mostly likely use the best one as our final dataset 
imp1_model <- clean_data(imp_data1)
imp2_model <- clean_data(imp_data2)
imp3_model <- clean_data(imp_data3)
imp4_model <- clean_data(imp_data4)
imp5_model <- clean_data(imp_data5)
```


```{r}

#Our end goal is to be able to predict MH Score, so we are going to look for the model with the lowest prediction error rate

build_model <- function(data_model){
  #Split data into 80/20 training/test
  smp_siz = floor(0.8 * nrow(data_model))
  set.seed(123)
  train_ind = sample(seq_len(nrow(data_model)), size = smp_siz)
  df_train = data_model[train_ind,]
  df_test = data_model[-train_ind,]

  lm_mod <- lm(formula = MHscore ~ SOC_Score + PHYS_Score + RESP_Score + ECON_Score +  P_DENSE +
                 REGION9 + HHSIZE1 + EDUCATION + GENDER + AGE7, data = df_train)
  
  pred_mh1 <- predict(lm_mod, data = df_test)
  actuals_preds1 <- data.frame(cbind(actuals = df_test$MHscore, predicteds = pred_mh1))
  mape1 <- mean(abs((actuals_preds1$predicteds - actuals_preds1$actuals))/actuals_preds1$actuals)

  return(mape1)
}

lm_mape1 <- build_model(imp1_model)
lm_mape2 <- build_model(imp2_model)
lm_mape3 <- build_model(imp3_model)
lm_mape4 <- build_model(imp4_model)
lm_mape5 <- build_model(imp5_model)

mapes <- c(lm_mape1, lm_mape2, lm_mape3, lm_mape4, lm_mape5)

which.min(mapes)

#We now know that model 2 has the best prediction rate, so that will be the model we use. 

final_mod <- lm(formula = MHscore ~ SOC_Score + PHYS_Score + RESP_Score + ECON_Score +  P_DENSE +
                 REGION9 + HHSIZE1 + EDUCATION + GENDER + AGE7, data = imp2_model)
summary(final_mod)

```

```{r}

#Now let's look at some of the feature correlation directly with MH Score
data_model <- imp2_model
p <- list()
var_names <- names(data_model)
var_names <- var_names[2:11]
for (i in 1:length(var_names)) {
  gg <- ggplot(data_model, aes_string(x=as.name(var_names[i]), y="MHscore"))
  p[[i]] <- gg + geom_point(alpha=0.15, position="jitter", color="#002366") + labs(x=var_names[i])
}

marrangeGrob(grobs = p, nrow=2, ncol=2)

```


```{r}
#Let's look at the distribution of these features
h <- list()
for (i in 1:length(var_names)) {
  gg <- ggplot(data_model, aes_string(x=as.name(var_names[i])))
  h[[i]] <- gg + geom_histogram(color="#002366", fill="white") + labs(x=var_names[i])
}

marrangeGrob(grobs = h, nrow=2, ncol=2)
```

```{r}
#Because SOC Score and RESP Score seem to have low correlation, let's look at some models that remove them
#Removes both
final_mod1 <- lm(formula = MHscore ~  PHYS_Score + ECON_Score +  P_DENSE +
                 REGION9 + HHSIZE1 + EDUCATION + GENDER + AGE7, data = imp2_model)
#Removes SOC
final_mod2 <- lm(formula = MHscore ~ PHYS_Score + RESP_Score + ECON_Score +  P_DENSE +
                 REGION9 + HHSIZE1 + EDUCATION + GENDER + AGE7, data = imp2_model)
#Removes RESP
final_mod3 <- lm(formula = MHscore ~ SOC_Score + PHYS_Score + ECON_Score +  P_DENSE +
                 REGION9 + HHSIZE1 + EDUCATION + GENDER + AGE7, data = imp2_model)
summary(final_mod1)
summary(final_mod2)
summary(final_mod3)
```