---
title: "Week 2 Spring Cleaning"
author: "Prashit Parikh"
date: "May 28, 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(DescTools)
```

```{r}
urlfile <- "https://raw.githubusercontent.com/jlin99/DataFest-2020/master/data/covid%20impact%20survey/week1.csv"

urlfile2 <- "https://raw.githubusercontent.com/jlin99/DataFest-2020/master/data/covid%20impact%20survey/week2.csv"

wk1 <- read_csv(url(urlfile))

wk2 <- read_csv(url(urlfile2))

column.numeric <- function(column){
  return(parse_number(column))
}

column.clean <- function(column){
  column.new <- ifelse(column>70, NA, column)
  return(column.new)
}
```

```{r}
##These columns need to be converted to numbers Week 1

pt1 <- as.data.frame(lapply(wk1[c(7:95)], column.numeric))

pt2 <- as.data.frame(lapply(wk1[c(97:97)], column.numeric))

pt3 <- as.data.frame(lapply(wk1[c(99:122)], column.numeric))

pt4 <- as.data.frame(lapply(wk1[c(124:152)], column.numeric))

pt5 <- as.data.frame(lapply(wk1[c(154:155)], column.numeric))

pt6 <- as.data.frame(lapply(wk1[c(157:157)], column.numeric))

pt7 <- as.data.frame(lapply(wk1[c(163:169)], column.numeric))

pt8 <- as.data.frame(lapply(wk1[c(171:173)], column.numeric))

full <- bind_cols(pt1, pt2)
full <- bind_cols(full, pt3)
full <- bind_cols(full, pt4)
full <- bind_cols(full, pt5)
full <- bind_cols(full, pt6)
full <- bind_cols(full, pt7)
full <- bind_cols(full, pt8)

full <- as.data.frame(lapply(full[c(1:155)], column.clean))

wk1.new <- bind_cols(wk1[c(1:6)], full)
wk1.new <- bind_cols(wk1.new, wk1[96])
wk1.new <- bind_cols(wk1.new, wk1[98])
wk1.new <- bind_cols(wk1.new, wk1[123])
wk1.new <- bind_cols(wk1.new, wk1[153])
wk1.new <- bind_cols(wk1.new, wk1[c(158:162)])

wk1.new$HHINCOME <- ifelse(wk1.new$HHINCOME=="Under $10,000", 1,
                           ifelse(wk1.new$HHINCOME=="$10,000 to under $20,000", 2,
                           ifelse(wk1.new$HHINCOME=="$20,000 to under $30,000", 3,
                           ifelse(wk1.new$HHINCOME=="$30,000 to under $40,000", 4,
                           ifelse(wk1.new$HHINCOME=="$40,000 to under $50,000", 5,
                           ifelse(wk1.new$HHINCOME=="$50,000 to under $75,000", 6,
                           ifelse(wk1.new$HHINCOME=="$75,000 to under $100,000", 7,
                           ifelse(wk1.new$HHINCOME=="$100,000 to under $150,000", 8,
                           ifelse(wk1.new$HHINCOME=="$150,000 or more", 9, NA)))))))))

wk1.new$NeighborChange <- wk1.new$SOC2B - wk1.new$SOC2A

write.csv(wk1.new, file = "wk1.new_final.csv")
```

```{r}
##These columns need to be converted to numbers Week 2

pt9 <- as.data.frame(lapply(wk2[c(9:97)], column.numeric))

pt10 <- as.data.frame(lapply(wk2[c(99:154)], column.numeric))

pt11 <- as.data.frame(lapply(wk2[c(156:157)], column.numeric))

pt12 <- as.data.frame(lapply(wk2[c(161:161)], column.numeric))

pt13 <- as.data.frame(lapply(wk2[c(167:173, 175:177)], column.numeric))

full2 <- bind_cols(pt9, pt10)
full2 <- bind_cols(full2, pt11)
full2 <- bind_cols(full2, pt12)
full2 <- bind_cols(full2, pt13)

full2 <- as.data.frame(lapply(full2[c(1:158)], column.clean))

wk2.new <- bind_cols(wk2[c(1:8)], full2)
wk2.new <- bind_cols(wk2.new, wk2[98])
wk2.new <- bind_cols(wk2.new, wk2[100])
wk2.new <- bind_cols(wk2.new, wk2[155])
wk2.new <- bind_cols(wk2.new, wk2[c(158:160)])
wk2.new <- bind_cols(wk2.new, wk2[c(162:166)])
wk2.new <- bind_cols(wk2.new, wk2[(174)])

wk2.new$HHINCOME <- ifelse(wk2.new$HHINCOME=="Under $10,000", 1,
                           ifelse(wk2.new$HHINCOME=="$10,000 to under $20,000", 2,
                           ifelse(wk2.new$HHINCOME=="$20,000 to under $30,000", 3,
                           ifelse(wk2.new$HHINCOME=="$30,000 to under $40,000", 4,
                           ifelse(wk2.new$HHINCOME=="$40,000 to under $50,000", 5,
                           ifelse(wk2.new$HHINCOME=="$50,000 to under $75,000", 6,
                           ifelse(wk2.new$HHINCOME=="$75,000 to under $100,000", 7,
                           ifelse(wk2.new$HHINCOME=="$100,000 to under $150,000", 8,
                           ifelse(wk2.new$HHINCOME=="$150,000 or more", 9, NA)))))))))

wk2.new$PHYS11_TEMP <- wk2$PHYS11_TEMP
wk2.new$PHYS11_TEMP <- parse_number(wk2.new$PHYS11_TEMP)
wk2.new$PHYS11_TEMP <- ifelse(wk2.new$PHYS11_TEMP>100, NA, wk2.new$PHYS11_TEMP)
wk2.new$ECON2 <- as.numeric(wk2.new$ECON2)
wk2.new$ECON3 <- as.numeric(wk2.new$ECON3)

wk2.new$NeighborChange <- wk2.new$SOC2B - wk2.new$SOC2A

write.csv(wk2.new, file = "wk2.new_final.csv")
```
