---
title: "model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

```{r}
urlfile <- "https://raw.githubusercontent.com/jlin99/DataFest-2020/master/data/covid%20impact%20survey/wk1.new.csv"
data <- read.csv(url(urlfile))
#Delete question answers deemed unusable for our model (due to complexity, irrelevance, redundancy, etc.)
#PHYS11, PHYS11TEMP, ECON2, ECON4, HH****, MODE, LANGUAGE, etc.

drops <- c("PHYS11", "PHYS11_TEMP", "HH01S", "HH25S", "HH612S", "HH1317S", "HH18OVS", "P_OCCUPY2", "MODE", "MAIL50", "HH_BANNER", "EDUC4", "INC_BANNER", "AGE_BANNER", "AGE4", "RACE2_BANNER", "RACETH", "RACE_R2", "NATIONAL_WEIGHT", "REGION_WEIGHT", "NATIONAL_WEIGHT_POP", "REGION_WEIGHT_POP", "NAT_WGT_COMB_POP", "REG_WGT_COMB_POP", "P_GEO", "P_PANEL", "SU_ID", "LANGUAGE", "ECON2", "ECON4")
data_mod <- data[ , !(names(data) %in% drops)]

#Form our predictor value, Mental Health Score
#Sum the answers to SOC5A-SOC5E. A lower number indicates better mental health 

data_mod <- data_mod %>%
  mutate(MH_Score = rowSums(.[27:31]))

#Next we form our first feature, SOC Score
#Because we are looking at mental health in COVID times, socialization pre-COVID does not help us
#Instead we are replacing those columns with change in socialization (delta)
#We do A - B because we want a lower score to indicate good social health (talking to people)
#If there is a dramatic shift from frequently socializing (1) to not socializing at all (5), we want to mark that as a higher score since that is presumably bad. Hence, 5-1 makes more sense.

data_mod$SOC2_delta <- data_mod$SOC2A - data_mod$SOC2B
data_mod$SOC3_delta <- data_mod$SOC3A - data_mod$SOC2B

#In order to remain with theme of lower social health is better, we need to reverse answers of PHYS6

for (i in 1:length(data_mod$PHYS6)){
  if ( isTRUE(data_mod$PHYS6[i] == 1)){
    data_mod$PHYS6[i] = 2
  }
  else if ( isTRUE(data_mod$PHYS6[i] == 2)){
    data_mod$PHYS6[i] = 1
  }
}

#Next, our SOC score is made up of SOC1, SOC2A, SOC2_delta, SOC3A, SOC3_delta, SOC4A, SOC4B, PHYS6
#min score = -2, max score = 28

data_mod <- data_mod %>%
  mutate(SOC_Score = rowSums(cbind(data_mod$SOC1, data_mod$SOC2, data_mod$SOC2_delta, data_mod$SOC3A, data_mod$SOC3_delta, data_mod$SOC4A, data_mod$SOC4B, data_mod$PHYS6)))

#Make PHYS score
#For similar reasons, I need to reverse some of the columns in this section

phys_rev <- c(10:26, 121:135)

for (i in phys_rev){
  for (j in 1:length(data_mod[,i])){
    if (isTRUE(data_mod[j,i] == 1)){
      data_mod[j,i] = 2
      }
    else if (isTRUE(data_mod[j,i] == 2)){
      data_mod[j,i] = 1
    }
  }
}


#Made up of PHYS8, PHYS1A:PHYS1Q, PHYS7_1:PHYS7_4, PHYS3A:PHYS3M, PHYS4, PHYS5
#min score = 33, max score = 75


phys_col <- c(9:26,106:109,121:135)

data_mod <- data_mod %>%
  mutate(PHYS_Score = rowSums(data_mod[,phys_col]))
         
#Make RESPONSE score 

#There is one answer that also needs to be reversed

resp_rev <- c(32:50)

for (i in resp_rev){
  for (j in 1:length(data_mod[,i])){
    if (isTRUE(data_mod[j,i] == 0)){
      data_mod[j,i] = 1
      }
    else if (isTRUE(data_mod[j,i] == 1)){
      data_mod[j,i] = 0
    }
  }
}


#Made up of PHYS2_1:PHYS2_19, PHYS10A:PHYS10E, ECON8A:ECON8S
#min score = 24, max score = 82

resp_col <- c(32:50, 54:77)

data_mod <- data_mod %>%
   mutate(RESP_Score = rowSums(data_mod[,resp_col]))
#Make ECON score

#We also need to reverse some of the ECON scores

econ_rev1<- c(92:103)
econ_rev2 <- c(104,105)

for (i in econ_rev1){
  for (j in 1:length(data_mod[,i])){
    if (isTRUE(data_mod[j,i] == 1)){
      data_mod[j,i] = 4
      }
    else if (isTRUE(data_mod[j,i] == 2)){
      data_mod[j,i] = 3
    }
    else if (isTRUE(data_mod[j,i] == 3)){
      data_mod[j,i] = 2
    }
    else if (isTRUE(data_mod[j,i] == 4)){
      data_mod[j,i] = 1
    }
  }
}

for (i in econ_rev2){
  for (j in 1:length(data_mod[,i])){
    if (isTRUE(data_mod[j,i] == 1)){
      data_mod[j,i] = 3
      }
    else if (isTRUE(data_mod[j,i] == 3)){
      data_mod[j,i] = 1
    }
  }
}

dict = c(18:1)

for (j in 1:length(data_mod[,146])){
    data_mod[j,146] = dict[data_mod[j,146]]
}
#Made up of ECON7, ECON1, ECON4A, ECON4B, ECON6A:ECON6L, ECON5A:ECON5B, INCOME
#min score = 18, max score = 93

econ_col <- c(78:85, 89:105, 146)

data_mod <- data_mod %>%
   mutate(ECON_Score = rowSums(data_mod[,econ_col]))

#Lastly, we include gender, race, educat, hhsize, etc. in our data frame for our model

model_col <- c(147, 150:153, 144, 143, 142, 140, 139, 138, 137)

data_model <- data_mod[,model_col]

#Scale SOC, PHYS, RESP, and ECON scores so people can rate themselves on a scale from 0-10
scalescores <- c(2:5)
for (i in scalescores){
  data_model[,i] <- (data_model[,i]-min(data_model[,i], na.rm=T))*10/
      (max(data_model[,i], na.rm=T)-min(data_model[,i], na.rm=T))
}
```
